# Ce workflow utilise des actions qui ne sont pas certifiées par GitHub.
# Elles sont fournies par un tiers et régies par
# des conditions d’utilisation du service, une politique de confidentialité et un support distincts.
# documentation en ligne.

# GitHub recommande d’épingler les actions à un SHA de commit.
# Pour obtenir une version plus récente, vous devez mettre à jour le SHA.
# Vous pouvez également référencer une balise ou une branche, mais l’action peut changer sans avertissement.

name: Java CI

run-name: Gradle tests and build GitHub Actions ⚙️

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out du repository de la branche concernée
        uses: actions/checkout@v3.5.1
      - name: Utilisation du JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validation du Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Lancement du build Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build
        env:
          TMDB_JETON_ACCES: ${{ secrets.TMDB_JETON_ACCES }}
